
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/finalshop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100




  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#    serialization:
#      fail-on-empty-beans: false
# ??? ???? ??? ??? ??...
#  @Bean
#  Hibernate5Module hibernate5Module() {
#  return new Hibernate5Module();
#}





logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace